Ensure anomalies are also run through Drain to reduce the amount of error messages

diff --git a/examples/chown/test-chown.yaml b/examples/chown/test-chown.yaml
--- a/examples/chown/test-chown.yaml
+++ b/examples/chown/test-chown.yaml
@@ -19,7 +19,6 @@ metadata:
 data:
   test_chown: |
     #! /bin/bash
-    set -e # Exit on error
     set -u # Treat unset variables as an error
     set -o pipefail # Fail on any command in a pipeline that fails
 
@@ -38,15 +37,18 @@ data:
       echo "[$( date --rfc-3339=s)] File $FILE_PATH exists, proceeding to change ownership."
     fi
 
-    # Try to change the ownership of the file
-    chown -v ${2} "$FILE_PATH" || {
-      echo "[$( date --rfc-3339=s)] Error: Failed to change ownership of $FILE_PATH"
-      exit 1
-    }
+    while true
+    do
+      # Try to change the ownership of the file
+      chown -v ${2} "$FILE_PATH" 
+      if [ $? -eq 0 ]; then
+        echo "[$( date --rfc-3339=s)] Ownership of $FILE_PATH changed to root:root successfully."
+      else
+        echo "[$( date --rfc-3339=s)] Error: Failed to change ownership of $FILE_PATH"
+      fi
 
-    echo "[$( date --rfc-3339=s)] Ownership of $FILE_PATH changed to root:root successfully."
-
-    sleep 600 # Sleep for 10 minutes to keep the script running
+      sleep 5 # Sleep for 5 seconds before the next attempt
+    done
 ---
 apiVersion: apps/v1
 kind: Deployment
diff --git a/examples/port-check-privileged/privileged-port-check.yaml b/examples/port-check-privileged/privileged-port-check.yaml
--- a/examples/port-check-privileged/privileged-port-check.yaml
+++ b/examples/port-check-privileged/privileged-port-check.yaml
@@ -19,7 +19,6 @@ metadata:
 data:
   bind_to_port: |
     #! /bin/bash
-    set -e # Exit on error
     set -u # Treat unset variables as an error
     set -o pipefail # Fail on any command in a pipeline that fails
 
@@ -39,22 +38,17 @@ data:
     # Open the port for binding without checking if it is already in use
     ncat -k -l 127.0.0.1 "$PORT" &
 
-    # Check if ncat command was successful
-    if [ $? -eq 0 ]; then
-      echo "[$( date --rfc-3339=s)] Port $PORT is now open for binding."
-    else
-      echo "[$( date --rfc-3339=s)] Failed to open port $PORT."
-      exit 1
-    fi
+    while true
+    do
+      # Check if ncat command was successful
+      if [ $? -eq 0 ]; then
+        echo "[$( date --rfc-3339=s)] Port $PORT is now open for binding."
+      else
+        echo "[$( date --rfc-3339=s)] Failed to open port $PORT."
+      fi
 
-    # Wait for the background process to finish
-    nc -vz 127.0.0.1 "$PORT" || {
-      echo "[$( date --rfc-3339=s)] Port $PORT is not open or not reachable."
-      exit 1
-    }
-
-    sleep 600 # Sleep for 10 minutes to keep the script running
-    kill %1 # Kill the background ncat process
+      sleep 5 # Sleep for 5 seconds before checking again
+    done
 ---
 apiVersion: apps/v1
 kind: Deployment
